export const LOCALSTORAGE_KEY = "results";

export const HEROES = [
  { name: "Dancin’ Deryl", tier: 1 },
  { name: "Mutanus the Devourer", tier: 1 },
  { name: "Forest Warden Omu", tier: 1 },
  { name: "C’Thun", tier: 1 },
  { name: "Captain Hooktusk", tier: 1 },
  { name: "Kurtrus Ashfallen", tier: 1 },
  { name: "Jandice Barov", tier: 2 },
  { name: "Edwin VanCleef", tier: 2 },
  { name: "George the Fallen", tier: 2 },
  { name: "Death Speaker Blackthorn", tier: 2 },
  { name: "The Great Akazamzarak", tier: 2 },
  { name: "Shudderwock", tier: 2 },
  { name: "Arch-Villain Rafaam", tier: 2 },
  { name: "Al’Akir the Windlord", tier: 2 },
  { name: "Millhouse Manastorm", tier: 2 },
  { name: "Ragnaros the Firelord", tier: 2 },
  { name: "The Lich King", tier: 2 },
  { name: "Xyrella", tier: 2 },
  { name: "Vol’jin", tier: 2 },
  { name: "Silas Darkmoon", tier: 2 },
  { name: "Sir Finley Mrrgglton", tier: 2 },
  { name: "Tickatus", tier: 2 },
  { name: "Queen Wagtoggle", tier: 2 },
  { name: "Reno Jackson", tier: 2 },
  { name: "Greybough", tier: 2 },
  { name: "Galakrond", tier: 2 },
  { name: "Lord Barov", tier: 2 },
  { name: "Patches the Pirate", tier: 2 },
  { name: "Overlord Saurfang", tier: 2 },
  { name: "King Mukla", tier: 2 },
  { name: "Zephrys, the Great", tier: 2 },
  { name: "Malygos", tier: 2 },
  { name: "Kael’thas Sunstrider", tier: 3 },
  { name: "Rakanishu", tier: 3 },
  { name: "Nozdormu", tier: 3 },
  { name: "Alexstrasza", tier: 3 },
  { name: "Yogg-Saron, Hope’s End", tier: 3 },
  { name: "Maiev Shadowsong", tier: 3 },
  { name: "N’Zoth", tier: 3 },
  { name: "Trade Prince Gallywix", tier: 3 },
  { name: "Tess Greymane", tier: 3 },
  { name: "Millificent Manastorm", tier: 3 },
  { name: "Y’Shaarj", tier: 3 },
  { name: "Mr. Bigglesworth", tier: 3 },
  { name: "Infinite Toki", tier: 3 },
  { name: "Skycap’n Kragg", tier: 3 },
  { name: "Guff Runetotem", tier: 3 },
  { name: "Deathwing", tier: 3 },
  { name: "Sindragosa", tier: 3 },
  { name: "Patchwerk", tier: 3 },
  { name: "Illidan Stormrage", tier: 3 },
  { name: "Ysera", tier: 3 },
  { name: "Dinotamer Brann", tier: 3 },
  { name: "The Curator", tier: 3 },
  { name: "Captain Eudora", tier: 3 },
  { name: "Aranna Starseeker", tier: 3 },
  { name: "Lord Jaraxxus", tier: 3 },
  { name: "Fungalmancer Flurgl", tier: 4 },
  { name: "A. F. Kay", tier: 4 },
  { name: "Lich Baz’hial", tier: 4 },
  { name: "The Rat King", tier: 4 },
  { name: "Elise Starseeker", tier: 4 },
  { name: "Chenvaala", tier: 4 },
  { name: "Pyramad", tier: 4 },
];

export const STANDINGS = [
  {
    value: 1,
    label: 1,
  },
  {
    value: 2,
    label: 2,
  },
  {
    value: 3,
    label: 3,
  },
  {
    value: 4,
    label: 4,
  },
  {
    value: 5,
    label: 5,
  },
  {
    value: 6,
    label: 6,
  },
  {
    value: 7,
    label: 7,
  },
  {
    value: 8,
    label: 8,
  },
];
